dsn: "sqlite:///Users/href/dev/styx/priv/hydra.sqlite?_fk=true&mode=rwc"

serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:5000/account/oauth2/consent
  login: http://127.0.0.1:5000/account/oauth2/login
  logout: http://127.0.0.1:5000/account/oauth2/logout
  error: http://127.0.0.1:5000/account/oauth2/error

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis

